version: "3"

services:
  ### Schul-Cloud Server
  ###
  server-mongodb:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - data-server-mongodb:/data/db
    restart: unless-stopped

  server-rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "5672:5672"
      - "15672:15672" # management plugin user: guest / guest
    restart: unless-stopped

  server:
    build:
      context: ./schulcloud-server
      dockerfile: ../Dockerfile.server
    volumes:
      - ./schulcloud-server:/schulcloud-server
    depends_on:
      - server-mongodb
      - server-rabbitmq
    environment:
      # ENV
      - NODE_ENV=development
      - HOST=http://localhost:3030
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud

      # SMTP
      # - SMTP=
      # - SMTP_SENDER=

      # Storage
      - AWS_ENDPOINT_URL=https://dev-storage.schul-cloud.org:9001
      #- AWS_ENDPOINT_URL=http://localhost:9000
      ## keys for local s3 storage
      # - AWS_ACCESS_KEY=
      # - AWS_SECRET_ACCESS_KEY=

      # URIs and Port
      - MONGO_HOST=server-mongodb # for DB setup
      - MONGO_URI=mongodb://server-mongodb:27017/schulcloud
      - DB_URL=mongodb://server-mongodb:27017/schulcloud
      #- CALENDAR_URI=http://calendar:3000
      - CONTENT_URI=https://consent.schul-cloud.org
      - NOTIFICATION_URI=http://notification:3030
      - PORT=3030

      # RocketChat
      #- ROCKET_CHAT_URI=https://chat.schulcloud.local
      # - ROCKET_CHAT_ADMIN_TOKEN=
      # - ROCKET_CHAT_ADMIN_TOKEN=
      # - ROCKET_CHAT_ADMIN_ID=

      # Matrix Messenger
      - FEATURE_MATRIX_MESSENGER_ENABLED=true
      - MATRIX_URI=http://synapse:8008
      - MATRIX_SERVERNAME=matrix.local
      - MATRIX_SECRET=HmRJMD4ivBA0Y6viUuEkbbPsTUqatGOvMeO3HJTIVOzEhZdCMG2zZ0OXBdmJdlKg
      - FEATURE_RABBITMQ_ENABLED=true
      - RABBITMQ_URI=amqp://server-rabbitmq

      # AUTH Secret
      # - AUTHENTICATION=
      - IGNORE_DISCOVERABILITY=true

      # File preview service
      - ENABLE_THUMBNAIL_GENERATION=true
      - FILE_PREVIEW_SERVICE_URI=http://filepreview:3000/filepreview
      - FILE_PREVIEW_CALLBACK_URI=http://server:3030/fileStorage/thumbnail/

      # FEATURE TOGGLES
      - LERNSTORE_MODE=LEGACY
    ports:
      - "3030:3030"
      - "5959:5959"
    networks:
      - storage
      - default
    restart: unless-stopped
    command: sh -c "npm install --no-audit --prefer-offline && npm run debug:container"
  ###

  ### Schul-Cloud Client
  ###
  client:
    #image: schulcloud/schulcloud-client:develop
    build:
      context: ./schulcloud-client
      dockerfile: ../Dockerfile.client
    volumes:
      - ./schulcloud-client:/schulcloud-client
    depends_on:
      - server
    environment:
      # ENV
      - NODE_ENV=development
      - DOCKER=true
      #- CALENDAR_SERVICE_ENABLED=true
      - TZ=Europe/Berlin

      # Theme and Titles
      - SC_TITLE=HPI Schulcloud
      - SC_SHORT_TITLE=Schulcloud
      - SC_PRODUCTNAME=Hauptschule
      - SC_FEDERALSTATE=mainstate

      # URIs
      - HOST=http://localhost:3100
      - BACKEND_URL=http://server:3030
      - PUBLIC_BACKEND_URL=https://localhost:3030
      #- LIBRE_OFFICE_CLIENT_URL=http://localhost:9980
      #- ROCKET_CHAT_URI=https://chat.schulcloud.local

      # Matrix Messenger
      - FEATURE_MATRIX_MESSENGER_ENABLED=true
      - FEATURE_MESSENGER_SCHOOL_ROOM_ENABLED=true
      - FEATURE_MESSENGER_SCHOOL_SETTINGS_VISIBLE=true
      - MATRIX_MESSENGER_EMBED_URI=https://embed.test.messenger.schule # or http://localhost:8099
      - MATRIX_MESSENGER_HOMESERVER_URI=http://localhost:8008

      # FEATURE TOGGLES
      - FEATURE_TEAMS_ENABLED=true
      - LERNSTORE_MODE=LEGACY
      #- ROCKETCHAT_SERVICE_ENABLED=true
      - EDTR_SOURCE=https://cdn.jsdelivr.net/gh/schul-cloud/edtrio@e9d3bb9d66092bafa07846269c8fc6f9d5fb0559/dist/index.js
    ports:
      - "3100:3100"
      - "9310:9310" # debug port
      - "7000:7000"
    restart: unless-stopped
    command: sh -c "npm install --no-audit --prefer-offline && gulp watch-reload"
  ###

  ### Matrix Messenger
  sync:
    build:
      context: ./schulcloud-synapse-synchronization
      dockerfile: ../Dockerfile.sync
    volumes:
      - ./schulcloud-synapse-synchronization:/schulcloud-synapse-synchronization
    depends_on:
      - server-rabbitmq
      - synapse
    environment:
      # ENV
      - NODE_ENV=development

      # RabbitMQ
      - RABBITMQ_URI=amqp://server-rabbitmq
      - RABBIT_MQ_QUEUE=matrix_sync_populated
      - MATRIX_SYNC_USER_DISPLAYNAME=HPI Sync Bot

      # Synapse
      - MATRIX_URI=http://synapse:8008
      - MATRIX_SERVERNAME=matrix.local
      - MATRIX_SYNC_USER_NAME=sync
      - MATRIX_SECRET=HmRJMD4ivBA0Y6viUuEkbbPsTUqatGOvMeO3HJTIVOzEhZdCMG2zZ0OXBdmJdlKg
    restart: unless-stopped
    command: sh -c "npm install --no-audit --prefer-offline && npm run start" # npm run startd in next version of sync

  synapse:
    build:
      context: ./synapse
      dockerfile: ../Dockerfile.synapse
    volumes:
      - ./synapse:/data
    ports:
      - "8008:8008"

  embed:
    image: schulcloud/riot-web:feature-embed_20cf5f9d81a24deeaefdcdd5af66ef1019cfb1f5
    ports:
      - "8099:80"
  ###

  ### Schul-Cloud OAuth
  ###
  hydra-postgres:
    image: postgres:9.6
    environment:
      - SECRETS_SYSTEM=supersecurityperfavore
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
      - TLS_ALLOW_TERMINATION_FROM=172.18.0.0/24
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=atleast8
      - URLS_SELF_ISSUER=http://localhost:9000
      - SC_FRONTEND=http://localhost:3100
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
      - SERVE_PARAMS=--dangerous-force-http
    ports:
      - 5433:5432
    volumes:
      - data-hydra:/var/lib/postgresql/data
    restart: on-failure

  hydra-migrate-database:
    image: oryd/hydra:v1.0.0-rc.14
    command: ["migrate", "sql", "--yes", "postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable"]

  hydra-host:
    container_name: hydra-host
    image: oryd/hydra:v1.0.0-rc.14
    ports:
      #- 9000:4444
      - 9001:4445
    environment:
      - SECRETS_SYSTEM=supersecurityperfavore
      - DSN=postgres://hydra:secret@hydra-postgres:5432/hydra?sslmode=disable
      - TLS_ALLOW_TERMINATION_FROM=172.18.0.0/24
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=atleast8
      - URLS_SELF_ISSUER=http://localhost:9000
      - SC_FRONTEND=http://localhost:3100
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
      - URLS_LOGIN=http://localhost:3100/oauth2/login
      - URLS_CONSENT=http://localhost:3100/oauth2/consent
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
    depends_on:
      - hydra-migrate-database
    restart: on-failure
    command: ["serve", "all", "--dangerous-force-http"]
    deploy:
      replicas: 1
      restart_policy:
        condition: any
  ###

  ### Schul-Cloud Calendar
  ###
  # calendar-postgres:
  #   image: postgres:9.5
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - "data-calendar-postgres:/var/lib/postgresql/data"
  #     - "postgres-init:/docker-entrypoint-initdb.d"
  #   environment:
  #     - POSTGRES_DB=schulcloud_calendar
  #     - POSTGRES_USER=node
  #     - POSTGRES_PASSWORD=genericpassword
  #   restart: unless-stopped

  # calendar:
  #   image: schulcloud/schulcloud-calendar
  #   ports:
  #     - "3000"
  #   depends_on:
  #     - calendar-postgres
  #   volumes:
  #     - "postgres-init:/docker-entrypoint-initdb.d"
  #   environment:
  #     # ENV
  #     - NODE_ENV=production
  #     # DB Credentials
  #     - DB_PASSWORD=genericpassword
  #     - DB_HOST=calendar-postgres
  #     - DB_USERNAME=node
  #     - DB_DATABASE=schulcloud_calendar
  #     # Paths
  #     - SCHULCLOUD_BASE_PATH=http://server:3030
  #     - NOTIFICATION_SERVICE_BASE_PATH=http://notification:3040
  #     - SCHULCLOUD_ALL_USERS_FOR_UUID=http://server:3030/resolve/users/
  #     - SCHULCLOUD_ALL_SCOPES_FOR_TOKEN=http://server:3030/resolve/scopes/
  #     - NOTIFICATION_SERVICE_NEW_NOTIFICATION=http://notification:3040/messages
  #   restart: unless-stopped
  #   command: npm start
  ###

  ### Schul-Cloud Notifications
  ###

  ###

  ### Schul-Cloud Content
  ###

  ###

  ### Filepreview
  ###
  # redis:
  #   image: redis:latest
  #   command: ["redis-server", "--appendonly", "yes"]
  #   hostname: redis
  #   restart: unless-stopped

  # filepreview:
  #   image: schulcloud/filepreview:latest
  #   build:
  #     context: ../filepreview
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../filepreview:/home/node/app
  #   environment:
  #     USERNAME: filepreview
  #     PASSWORD: strongPassword
  #     REDIS_HOST: redis
  #   ports:
  #     - "3000"
  #   networks:
  #     - default
  #     - storage
  #   depends_on:
  #     - redis
  #   restart: unless-stopped
  ###

networks:
  storage:
    ipam:
      driver: default
      config:
        - subnet: "172.16.13.0/24"

volumes:
  data-server-mongodb:
  data-calendar-postgres:
  data-s3-storage:
  db-data:
  postgres-init:
  data-hydra:
